<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>创建职位</title>
		<!--<link rel="stylesheet" href="css/common.min.css" />-->
		<link rel="stylesheet/less" type="text/css" href="less/common.less" />
		<link rel="stylesheet/less" type="text/css" href="less/createjob.less" />
		<script src="js/plugin/holder.min.js"></script><!--图片占位插件，请删除-->
		<script src="js/plugin/less-1.7.0.min.js"></script>
		<script src="js/jquery-2.1.4.min.js"></script>
		<script src="js/common.js"></script>
	</head>
	<body>
		<div class="wrapper">
			<header id="header">
				<div class="wrap">
					
				</div>
				<!-- loading -->
				<div id="loading"></div>
				<!-- loading end -->
			</header>
			<div id="container">
				<div class="wrap">
					<form action="" class="form form-createJob" id="formJob">
						<div class="caption">创建新职位</div>
						<fieldset>
							<div class="form-group">
								<div class="form-item">
									<div class="item-label"><label>职位名称：</label></div>
									<div class="item-cont"><input type="text" autofocus="autofocus" id="jobName" class="txt lg" placeholder="请输入职位名称" /></div>
								</div>
								<div class="form-item">
									<div class="item-label"><label>职位工资：</label></div>
									<div class="item-cont"><input type="text" id="laborage" class="txt lg" placeholder="请输入职位工资" /></div>
								</div>
								<div class="form-item">
									<div class="item-label"><label>工作地点：</label></div>
									<div class="item-cont"><input type="text" id="location" class="txt lg" placeholder="请输入工作地点" /></div>
								</div>
							</div>
							<div class="form-group">
								<div class="form-item">
									<div class="item-label"><label>职位描述：</label></div>
									<div class="item-cont"><textarea name="" style="height:170px; width:495px;" class="resize-none"></textarea></div>
								</div>
							</div>
						</fieldset>
						<button type="button" class="btn btn-def xl w-lg float-right" id="jobSubmit">保存</button>
					</form>
				</div>
			</div>
			<footer id="footer">
				
			</footer>
		</div>
		<script src="js/createjob.js"></script>
	</body>
</html>
