<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>创建职位</title>
		<link rel="stylesheet" type="text/css" href="js/plugin/simditor/simditor.css"/>
		<link rel="stylesheet" type="text/css" href="css/common.min.css" />
		<link rel="stylesheet" type="text/css" href="css/createjob.css" />
		<script src="js/jquery-2.1.4.min.js"></script>
		<script src="js/plugin/simditor/module.min.js"></script>
		<script src="js/plugin/simditor/hotkeys.min.js"></script>
		<script src="js/plugin/simditor/uploader.min.js"></script>
		<script src="js/plugin/simditor/simditor.min.js"></script>
		<script src="js/common.js"></script>
	</head>
	<body>
		<div class="wrapper">
			<header id="header">
				<div class="wrap">
					<div id="logo">
						<a href="#"><img src="img/ui/logo.png" alt="" /></a>
						<h1>职业技能测试平台</h1>
					</div>
					<div id="userNav">
						<ul>
							<li><a href="">访问极客学院</a></li>
							<li><a href="">我的测评</a></li>
							<li class="userName">UsernameX</li>
							<li><a href="">退出</a></li>
						</ul>
					</div>
				</div>
				<!-- loading -->
				<div id="loading"></div>
				<!-- loading end -->
			</header>
			<div id="container">
				<!-- wrap -->
				<div class="wrap">
					<form action="" class="form form-createJob" id="formJob">
						<div class="caption">创建新职位</div>
						<fieldset>
							<div class="form-group">
								<div class="form-item">
									<div class="item-label"><label>职位名称：</label></div>
									<div class="item-cont"><input type="text" autofocus="autofocus" id="jobName" class="txt lg" placeholder="请输入职位名称" /></div>
								</div>
								<div class="form-item">
									<div class="item-label"><label>职位工资：</label></div>
									<div class="item-cont"><input type="text" id="laborage" class="txt lg" placeholder="请输入职位工资" /></div>
								</div>
								<div class="form-item">
									<div class="item-label"><label>工作地点：</label></div>
									<div class="item-cont"><input type="text" id="location" class="txt lg" placeholder="请输入工作地点" /></div>
								</div>
							</div>
							<div class="form-group">
								<div class="form-item">
									<div class="item-label"><label>职位描述：</label></div>
									<div class="item-cont"><textarea id="editor"></textarea></div>
								</div>
							</div>
						</fieldset>
						<button type="button" class="btn btn-def lg w-lg float-right" id="jobSubmit">保存</button>
					</form>
				</div>
				<!-- wrap end -->
				<hr />
				<!-- wrap -->
				<div class="wrap">

				</div>
				<!-- wrap end -->
				<hr />
			</div>
			<footer id="footer">

			</footer>
		</div>
		<script src="js/createjob.js"></script>
	</body>
</html>
