<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>首页</title>
		<link rel="stylesheet" href="css/common.min.css" />
		<link rel="stylesheet" href="css/index.css" />
		<script src="js/jquery-2.1.4.min.js"></script>
	</head>
	<body id="index">
		<div class="wrapper">
			<header id="header">
				<div class="wrap">
					<div id="logo">
						<a href="#"><img src="img/ui/logo.png" alt="" /></a>
						<h1>职业技能测试平台</h1>
					</div>
					<div id="userNav">
						<ul>
							<li><a href="">访问极客学院</a></li>
							<li><a href="">我的测评</a></li>
							<li class="userName">UsernameX</li>
							<li><a href="">退出</a></li>
						</ul>
					</div>
				</div>
			</header>
			<div id="container">
				<div class="wrap">
					<div class="wrap-text">
						<h2>更清晰的了解自己 因对职位更加得心应手</h2>
						<h4>在这里，你可以针对感兴趣的职位，对自己的专业技能进行测评<br />通过测评结果，更有针对性的进行学习</h4>
					</div>
					<div class="entry">
						<a href="#" class="entryLink">登录</a>
						<a href="#" class="ask">企业资格申请</a>
					</div>
					<div class="overview">
						<ul>
							<li>
								<div class="imgWrap"><img src="img/overview_01.png" alt="" /></div>
								<h3>操作简单</h3>
								<p>仅需点击鼠标即可完成测试</p>
							</li>
							<li>
								<div class="imgWrap"><img src="img/overview_02.png" alt="" /></div>
								<h3>精准直观的测评结果</h3>
								<p>通过图表展示职业匹配程度</p>
							</li>
							<li>
								<div class="imgWrap"><img src="img/overview_03.png" alt="" /></div>
								<h3>自动生成个人档案</h3>
								<p>企业可以通过你的档案直接找到你</p>
							</li>
							<li>
								<div class="imgWrap"><img src="img/overview_04.png" alt="" /></div>
								<h3>智能推荐课程</h3>
								<p>根据结果有针对性的进行学习</p>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<footer id="footer">
				
			</footer>
		</div>
	</body>
</html>
