<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>职位列表</title>
        <!--<link rel="stylesheet" href="css/common.min.css" />-->
        <!--<link rel="stylesheet" href="css/joblist.min.css" />-->
        <link rel="stylesheet/less" href="less/common.less" />
        <link rel="stylesheet/less" href="less/joblist.less" />
        <script src="js/plugin/less-1.7.0.min.js"></script>
        <script src="js/jquery-2.1.4.min.js"></script>
        <script src="js/common.js"></script>
    </head>
    <body>
        <div class="wrapper">
            <header id="header">
                <div class="wrap">
                    <div id="logo">
                        <a href="#"><img src="img/ui/logo.png" alt="" /></a>
                        <h1>职业技能测试平台</h1>
                    </div>
                    <div id="userNav">
                        <ul>
                            <li><a href="">登录</a></li>
                        </ul>
                    </div>
                </div>
            </header>
            <div id="container">
                <div class="wrap">
                    <div class="jobList">
                        <header>
                            <h2 class="caption">我发布的职位</h2>
                            <a href="#" class="btn btn-def xl w-lg">+ 创建新职位</a>
                        </header>
                        <article id="jobList">
                            <!--<p class="dataNull"><i class="icon i-edit"></i>您还没有创建过任何职位</p>-->
                            <div class="mod-job">
                                <div class="job-name">高级Web前端工程师</div>
                                <div class="job-operate">
                                    <div class="job-toolbar">
                                        <a href="#" class="switch"><i class="icon"></i>开启</a>
                                        <a href="#" class="delete"><i class="icon i-del"></i>删除</a>
                                        <a href="#" class="editor"><i class="icon i-edit-sm"></i>编辑</a>
                                    </div>
                                    <div class="statistic">
                                        <p><strong>175</strong></p>
                                        <p>人参与了测评</p>
                                    </div>
                                    <a class="result" href="#"><i class="icon i-chart"></i>查看结果</a>
                                </div>
                            </div>
                            <div class="mod-job">
                                <div class="job-name">高级Web前端工程师</div>
                                <div class="job-operate">
                                    <div class="job-toolbar">
                                        <a href="#" class="switch off"><i class="icon"></i>开启</a>
                                        <a href="#" class="delete"><i class="icon i-del"></i>删除</a>
                                        <a href="#" class="editor"><i class="icon i-edit-sm"></i>编辑</a>
                                    </div>
                                    <div class="statistic">
                                        <p><strong>175</strong></p>
                                        <p>人参与了测评</p>
                                    </div>
                                    <a class="result" href="#"><i class="icon i-chart"></i>查看结果</a>
                                </div>
                            </div>
                            <div class="mod-job">
                                <div class="job-name">高级Web前端工程师</div>
                                <div class="job-operate">
                                    <div class="job-toolbar">
                                        <a href="#" class="switch"><i class="icon"></i>开启</a>
                                        <a href="#" class="delete"><i class="icon i-del"></i>删除</a>
                                        <a href="#" class="editor"><i class="icon i-edit-sm"></i>编辑</a>
                                    </div>
                                    <div class="statistic">
                                        <p><strong>175</strong></p>
                                        <p>人参与了测评</p>
                                    </div>
                                    <a class="result" href="#"><i class="icon i-chart"></i>查看结果</a>
                                </div>
                            </div>
                            <div class="mod-job">
                                <div class="job-name">高级Web前端工程师</div>
                                <div class="job-operate">
                                    <div class="job-toolbar">
                                        <a href="#" class="switch"><i class="icon"></i>开启</a>
                                        <a href="#" class="delete"><i class="icon i-del"></i>删除</a>
                                        <a href="#" class="editor"><i class="icon i-edit-sm"></i>编辑</a>
                                    </div>
                                    <div class="statistic">
                                        <p><strong>175</strong></p>
                                        <p>人参与了测评</p>
                                    </div>
                                    <a class="result" href="#"><i class="icon i-chart"></i>查看结果</a>
                                </div>
                            </div> <div class="mod-job">
                                <div class="job-name">高级Web前端工程师</div>
                                <div class="job-operate">
                                    <div class="job-toolbar">
                                        <a href="javascript:;" class="switch"><i class="icon"></i>开启</a>
                                        <a href="javascript:;" class="delete"><i class="icon i-del"></i>删除</a>
                                        <a href="javascript:;" class="editor"><i class="icon i-edit-sm"></i>编辑</a>
                                    </div>
                                    <div class="statistic">
                                        <p><strong>175</strong></p>
                                        <p>人参与了测评</p>
                                    </div>
                                    <a class="result" href="#"><i class="icon i-chart"></i>查看结果</a>
                                </div>
                            </div>
                        </article>
                    </div>
                </div>
            </div>
            <footer id="footer">

            </footer>
        </div>
        <script src="js/joblist.js"></script>
    </body>
</html>
