<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>职位列表</title>
		<link rel="stylesheet" href="css/common.min.css" />
		<link rel="stylesheet" href="css/joblist.min.css" />
		<script src="js/jquery-2.1.4.min.js"></script>
	</head>
	<body>
		<div class="wrapper">
			<header id="header">
				<div class="wrap">
					<div id="logo">
						<a href="#"><img src="img/ui/logo.png" alt="" /></a>
						<h1>职业技能测试平台</h1>
					</div>
					<div id="userNav">
						<ul>
							<li><a href="">登录</a></li>
						</ul>
					</div>
				</div>
			</header>
			<div id="container">
				<div class="wrap">
					<div class="jobList">
						<header>
							<h2 class="caption">我发布的职位</h2>
							<a href="#" class="btn btn-def xl w-lg" id="createJob">+ 创建新职位</a>
						</header>
						<article>
							<p class="dataNull"><i class="icon i-edit"></i>您还没有创建过任何职位</p>
						</article>
					</div>
				</div>
			</div>
			<footer id="footer">
					
			</footer>
		</div>
	</body>
</html>
