<!DOCTYPE html>
<html lang="zh-cn">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>选择用户角色</title>
        <link rel="stylesheet" href="css/common.min.css" />
        <script src="js/jquery-2.1.4.min.js"></script>
        <script src="js/common.js"></script>
    </head>
    <body>
        <div class="wrapper">
            <header id="header">
                <div class="wrap">
                    <div id="logo">
                        <a href="#"><img src="img/ui/logo.png" alt="" /></a>
                        <h1>职业技能测试平台</h1>
                    </div>
                    <div id="userNav">
                        <ul>
                            <li><a href="">登录</a></li>
                        </ul>
                    </div>
                </div>
                <!-- loading -->
                <div id="loading"></div>
                <!-- loading end -->
            </header>
            <div id="container">
                <div class="wrap">
                    <h2 class="caption">选择用户角色</h2>
                    <form action="" class="form form-role" id="formRole">
						<fieldset>
							<legend>选择用户角色</legend>
							<div class="form-item" id="roleSelect">
								<label class="btn btn-primary radio-role">我是学习者<br />我要进行技能测试<input type="radio" class="radio" id="learner" name="role" /></label>
								<label class="btn btn-primary radio-role">我是企业<br />我要发布职位<input type="radio" class="radio" id="company" name="role" /></label>
								<div class="note warnColor">您只有一次设定角色的机会，并无法修改，请务必根据真实情况进行选择</div>
							</div>
							<div class="form-item"><button type="button" class="btn btn-def lg w-lg float-right" id="submit">下一步</button></div>
						</fieldset>
                    </form>
				</div>
            </div>
            <footer id="footer">

            </footer>
        </div>
        <script src="js/role.js"></script>
    </body>
</html>
