<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>审核中</title>
		<link rel="stylesheet" href="css/common.min.css" />
		<script src="js/jquery-2.1.4.min.js"></script>
	</head>
	<body id="checking">
		<div class="wrapper">
			<header id="header">
				<div class="wrap">
					<div id="logo">
						<a href="#"><img src="img/ui/logo.png" alt="" /></a>
						<h1>职业技能测试平台</h1>
					</div>
					<div id="userNav">
						<ul>
							<li><a href="">登录</a></li>
						</ul>
					</div>
				</div>
                <!-- loading -->
                <div id="loading"></div>
                <!-- loading end -->
			</header>
			<div id="container">
				<div class="wrap">
					<p class="dataNull"><i class="icon i-eye"></i>您的企业身份正在审核中，请耐心等待...</p>
				</div>
			</div>
			<footer id="footer">

			</footer>
		</div>
	</body>
</html>
