<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>企业申请</title>
		<link rel="stylesheet" href="css/common.min.css" />
		<script src="js/jquery-2.1.4.min.js"></script>
		<script src="js/plugin/webuploader.min.js"></script>
		<script src="js/common.js"></script>
	</head>
	<body>
		<div class="wrapper">
			<header id="header">
				<div class="wrap">
					<div id="logo">
						<a href="#"><img src="img/ui/logo.png" alt="" /></a>
						<h1>职业技能测试平台</h1>
					</div>
					<div id="userNav">
						<ul>
							<li><a href="">访问极客学院</a></li>
							<li><a href="">我的测评</a></li>
							<li class="userName">UsernameX</li>
							<li><a href="">退出</a></li>
						</ul>
					</div>
				</div>
				<!-- loading -->
				<div id="loading"></div>
				<!-- loading end -->
			</header>
			<div id="container">
				<div class="wrap">
					<form action="" class="form form-lable-auto form-qiye">
						<div class="caption">提交企业信息</div>
						<fieldset>
							<div class="form-item">
								<div class="item-label"><label>企业名称：</label></div>
								<div class="item-cont"><input type="text" autofocus="autofocus" id="qyName" class="txt lg w-full" placeholder="请输入公司名称" /></div>
							</div>
							<div class="form-item">
								<div class="item-label"><label>企业简介：</label></div>
								<div class="item-cont"><textarea name="" id="qyOverview" class="w-full resize-none" style="height:145px" placeholder="请输入公司简介"></textarea></div>
							</div>
							<div class="form-group">
								<div class="form-item">
									<div class="item-label"><label>联系人电话：</label></div>
									<div class="item-cont"><input type="text" id="qyTel" class="txt lg w-lg" /></div>
								</div>
								<div class="form-item">
									<div class="item-label"><label>联系人：</label></div>
									<div class="item-cont"><input type="text" id="qyContact" class="txt lg w-lg" /></div>
								</div>
							</div>
							<div class="form-item">
								<div class="item-label"><label>联系人邮箱：</label></div>
								<div class="item-cont"><input type="text" id="qyEmail" class="txt lg w-lg" /></div>
							</div>
						</fieldset>
						<fieldset class="qyLogo">
							<div class="qy-logo" id="qyLogo">
								<img src="" alt="" />
								<div id="qyLogo-btn"></div>
							</div>
						</fieldset>
						<fieldset class="btn-submit">
							<button type="button" class="btn btn-def xl w-lg" id="qySubmit">提交申请</button>
						</fieldset>
					</form>
				</div>
			</div>
			<footer id="footer">
				
			</footer>
		</div>
		<script src="js/qy.js"></script>
	</body>
</html>
