<!DOCTYPE html>
<html lang="zh-cn">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
		<title>创建职位</title>
		<link rel="stylesheet" type="text/css" href="css/common.min.css" />
		<link rel="stylesheet" type="text/css" href="css/createjob.css" />
		<script src="js/jquery-2.1.4.min.js"></script>
		<script src="js/common.js"></script>
	</head>
	<body>
		<div class="wrapper">
			<header id="header">
				<div class="wrap">
					<div id="logo">
						<a href="#"><img src="img/ui/logo.png" alt="" /></a>
						<h1>职业技能测试平台</h1>
					</div>
					<div id="userNav">
						<ul>
							<li><a href="">访问极客学院</a></li>
							<li><a href="">我的测评</a></li>
							<li class="userName">UsernameX</li>
							<li><a href="">退出</a></li>
						</ul>
					</div>
				</div>
				<!-- loading -->
				<div id="loading"></div>
				<!-- loading end -->
			</header>
			<div id="container">
                <!-- wrap -->
                <div class="wrap">

                </div>
                <!-- wrap end -->
                <hr />
                <!-- wrap -->
                <div class="wrap">

                </div>
                <!-- wrap end -->
                <hr />
                <!-- wrap -->
                <div class="wrap">
                    <a href="#" class="btn btn-def xl w-full">开始测试</a>
                </div>
                <!-- wrap end -->
			</div>
			<footer id="footer">

			</footer>
		</div>
	</body>
</html>
